eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8001
spring:
  application:
    name: meta-server
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/morning
  redis:
    host: 127.0.0.1
    jedis: 
      pool: 
        max-active: 8
  rabbitmq:
    exchange: morning
    host: localhost
    port: 5672
    username: jiangpeng
    password: jiangpeng
#不能用localhost,否则启动报异常:Unresolved address
#tcp监听的端口
tcp:
  port: 8090
# bossGroup的线程数
boss:
  thread:
    count: 2
# worker的线程数
worker:
  thread:
    count: 2
#是否使用长连接
so:
  keepalive:  true
  backlog: 100