eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8001
spring:
  application:
    name: meta-server
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/morning
  redis:
    host: 127.0.0.1
    jedis: 
      pool: 
        max-active: 8