eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8002
spring:
  application:
    name: engine-server
  datasource:
    url: jdbc:mysql://localhost:3306/morning
    username: root
    password: jiangpeng
    driver-class-name: com.mysql.jdbc.Driver
    mongodb:
      url: mongodb://root:123456@localhost:27017/morning

logging:
  level:
    root: INFO
    morning: DEBUG